config/routes.rb
DonorSystem::Application.routes.draw do
  resources :donations

  resources :donors

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :donor

  def self.amount
    donation.sum
  end
end

app/models/donor.rb
class Donor < ActiveRecord::Base
  has_many :donations

  def amount2
      self.donations.sum(:amount)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donations }
    end
  end

  def donation_total
    @donation_sum = Donation.sum(:amount)
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
    @donation = Donation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/new
  # GET /donations/new.json
  def new
    @donation = Donation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/1/edit
  def edit
    @donation = Donation.find(params[:id])
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(params[:donation])

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render json: @donation, status: :created, location: @donation }
      else
        format.html { render action: "new" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /donations/1
  # PUT /donations/1.json
  def update
    @donation = Donation.find(params[:id])

    respond_to do |format|
      if @donation.update_attributes(params[:donation])
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy

    respond_to do |format|
      format.html { redirect_to donations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  # GET /donors
  # GET /donors.json
  def index
    @donors = Donor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donors }
    end
  end

  # GET /donors/1
  # GET /donors/1.json
  def show
    @donor = Donor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @donor }
    end
  end

  # GET /donors/new
  # GET /donors/new.json
  def new
    @donor = Donor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @donor }
    end
  end

  # GET /donors/1/edit
  def edit
    @donor = Donor.find(params[:id])
  end

  # POST /donors
  # POST /donors.json
  def create
    @donor = Donor.new(params[:donor])

    respond_to do |format|
      if @donor.save
        format.html { redirect_to @donor, notice: 'Donor was successfully created.' }
        format.json { render json: @donor, status: :created, location: @donor }
      else
        format.html { render action: "new" }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /donors/1
  # PUT /donors/1.json
  def update
    @donor = Donor.find(params[:id])

    respond_to do |format|
      if @donor.update_attributes(params[:donor])
        format.html { redirect_to @donor, notice: 'Donor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1
  # DELETE /donors/1.json
  def destroy
    @donor = Donor.find(params[:id])
    @donor.destroy

    respond_to do |format|
      format.html { redirect_to donors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :donor %><br />
      <%= f.collection_select :donor_id, Donor.all, :id, :name %>
    </div>

  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @donation.donor.name %>
</p>

<p>
  <b>Amount:</b>
  <%= @donation.amount %>
</p>

<p>
  <b>Date:</b>
  <%= @donation.created_at %>
</p>

<p>
  <b>Donation Total:</b>
  <%= @donation_sum %>
</p>


<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>

app/views/donors/_form.html.erb
<%= form_for(@donor) do |f| %>
  <% if @donor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donor.errors.count, "error") %> prohibited this donor from being saved:</h2>

      <ul>
      <% @donor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br />
    <%= f.text_field :email_address %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @donor.name %>
</p>

<p>
  <b>Email address:</b>
  <%= @donor.email_address %>
</p>

<p>
  <b>Total Donations:</b>
  <p><%= @donor.amount2 %></p>


</p>



<%= link_to 'Edit', edit_donor_path(@donor) %> |
<%= link_to 'Back', donors_path %>